### ISSUE TITLE
Different pick up and drop off for FLEX

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/OpenTripPlanner#101]
Gard has said in the OTP dev meeting that right now you can only have the same type of flex pick-up and drop-off in a single route.

However, in the Herrenberg case we have different pickup and drop off rules:

- Pick up is only possible at the bus stop
- Drop off is possible within 300m of a bus stop

**Comment by leonardehrenfried** [comment]
@derhuerst Are different pickup/dropoff rules, as described above, even possible in GTFS Flex?

**Comment by leonardehrenfried** [comment]
Ah, I checked stoptimes.txt and there are the columns `pickup_rule_id` and `dropoff_rule_id`. Presumably this means that it's possible, right?

**Comment by derhuerst** [comment]
[GTFS-Flex v2](https://github.com/MobilityData/gtfs-flex/blob/e1832cfea5ddb9df29bd2fc50e80b0a4987695c1/spec/reference.md) is split up into two parts:

- [GTFS-FlexibleTrips](https://github.com/MobilityData/gtfs-flex/blob/e1832cfea5ddb9df29bd2fc50e80b0a4987695c1/spec/reference.md#gtfs-flexibletrips) extends `stop_times.txt` to
    - support pickup/drop-off areas (by referencing items in `locations.geojson`)
    - support specifying a pickup/drop-off time window
- [GTFS-BookingRules](https://github.com/MobilityData/gtfs-flex/blob/e1832cfea5ddb9df29bd2fc50e80b0a4987695c1/spec/reference.md#gtfs-flexibletrips) extends the GTFS dataset to
    - define rules on when and how to book

Both just extend GTFS-Static, which already supports separate `pickup_type` & `drop_off_type`, so yes, **they do support having separate rules for pickup/drop-off**.

**Comment by flaktack** [comment]
The conclusion at Thursday's meeting was that this could only be handled using GTFS by having duplicated stop times:
* for pick up an actual `Stop` is included
* for drop off a `Location` is included

And so every stop would be present twice:
 * bus station stop (`drop_off_type=1`)
 * bus station location (`pickup_type=1`)
 * ...

**Comment by leonardehrenfried** [comment]
Do you mean with the current code or really conceptually only possible by having 2 stops?

**Comment by flaktack** [comment]
Conceptually -- I don't see how that could be modeled with a single stop time:
 * If a `Location` is referenced, how would you limit it to only pick up at the centerpoint, but allow drop off throughout the whole area?
* If a `Stop` is referenced, than how do you specify the area?

**Comment by flaktack** [comment]
A third option could be a `LocationGroup`, but there is still no option to differentiate between the elements (-> use the `Stop` for pickup, the `StopLocation` for drop off)

**Comment by derhuerst** [comment]
> A third option could be a `LocationGroup`, but there is still no option to differentiate between the elements (-> use the `Stop` for pickup, the `StopLocation` for drop off)

~~For pickup, you can directly reference a stop from `stops.txt`. For drop-off, you can reference a location group (from `location_groups.txt`) that includes both the stop (from `stops.txt`) as well as the location/area (from `locations.gejson`).~~

Edit: My bad, you can't, there's only one `stop_id` in `stop_times.txt`.

**Comment by leonardehrenfried** [comment]
@hbruch It seems that we're at a conceptual dead-end here. 

Unless someone has a better idea, I see the following options:

- extend the Flex spec with our own custom modification - huge implications as we would need to modify OBA, too
- make Herrenberg Bahnhof a fixed stop rather than a location with a radius

Can you advise?

**Comment by leonardehrenfried** [comment]
Closed in favour of https://github.com/derhuerst/generate-herrenberg-gtfs-flex/issues/5
