### ISSUE TITLE
Check car park availability calculation

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/OpenTripPlanner#104]
Feedback ID: 29

The system should exclude the closed parking places from the route suggestions 

![image](https://user-images.githubusercontent.com/84382750/122184028-1c459e80-ce8c-11eb-92d8-dcd9dcc680ed.png)

**Comment by leonardehrenfried** [comment]
This should just work without the clients having to set a parameter, isn't it?

Or am I overlooking something, @flaktack?

**Comment by leonardehrenfried** [comment]
Sorry, I was on the wrong branch. There is of course `useVehicleParkingAvailabilityInformation`, correct?

**Comment by flaktack** [comment]
Yes, `useVehicleParkingAvailabilityInformation` needs to be `true` to exclude the full parking lots.

**Comment by leonardehrenfried** [comment]
And what about those that are closed as per opening hours?

**Comment by flaktack** [comment]
That is always taken into account, there is no options to ignore the opening hours. Should there be?

**Comment by leonardehrenfried** [comment]
No.

**Comment by leonardehrenfried** [comment]
I was just wondering if in the example above the parking lot was closed or if it's full.
