### ISSUE TITLE
Filter out anything that doesn't end in a flex trip

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/OpenTripPlanner#111]
![Screenshot from 2021-06-23 13-20-55](https://user-images.githubusercontent.com/151346/123088337-e2ddd780-d425-11eb-9661-ed93773f0267.png)

Now I remember why I excluded bus trips from the flex query, as it might lead to trips like the above.

@hbruch We don't want those in the flex view, isn't it?

**Comment by hbruch** [comment]
We definitely don't won't trips without flex leg. Is 22:34-23:04 a stay-seated in RT794 suggestion with to door delivery? Then we should not remove it.

**Comment by leonardehrenfried** [comment]
That's something I'm investigating. @flaktack mentioned in the dev meeting that there is a problem with the transfer.

**Comment by leonardehrenfried** [comment]
acbed870389f19185fe9a90027d8798306552048 filters out anything that doesn't end in a flex trip.

**Comment by leonardehrenfried** [comment]
https://github.com/mfdz/OpenTripPlanner/commit/e1c9eb9c286aba14cadb18169fd2ab94eb7bd17f implements this logic.
