### ISSUE TITLE
No transfer from main station to flex taxi in front of station

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/OpenTripPlanner#112]
In flex mode we cannot transfer to the flex stop right in front of it.

![Screenshot from 2021-06-23 14-03-49](https://user-images.githubusercontent.com/151346/123093371-e6745d00-d42b-11eb-849c-ed679c60918e.png)

In normal bus mode this works however.
![Screenshot from 2021-06-23 14-03-39](https://user-images.githubusercontent.com/151346/123093377-e96f4d80-d42b-11eb-8c57-09f8f316df50.png)

So the problem is not the wait reluctance.

https://herrenberg.beta.stadtnavi.eu/reiseplan/Nufringen%3A%3A48.6224388%2C8.8881021/G%C3%BCltstein%3A%3A48.575747449999994%2C8.878864665540831/onDemandTaxi?time=1624479300

@flaktack is this one of the cases that you found that a transfer was not pre-computed?

**Comment by leonardehrenfried** [comment]
Probably a result of this is that you sometimes get trips that enter, exit and reenter the same trip. (Well, for OTP they are two trips.)

![Screenshot from 2021-06-23 14-17-22](https://user-images.githubusercontent.com/151346/123095011-dc535e00-d42d-11eb-8f31-f297f71e837f.png)

https://dev.stadtnavi.eu/reiseplan/Kalkofenstra%C3%9Fe%2C%2071083%20Herrenberg%3A%3A48.59449191456932%2C8.861846923828127/Gr%C3%BCnewaldstra%C3%9Fe%2012%2C%2071083%20Herrenberg%3A%3A48.5768626733423%2C8.880901336669924/onDemandTaxi?time=1624478400

**Comment by leonardehrenfried** [comment]
![Screenshot from 2021-06-23 14-53-14](https://user-images.githubusercontent.com/151346/123099815-d14efc80-d432-11eb-99be-d0669cbe622f.png)

The screenshot suggests that it's not a problem with the transfer. Is the flex stop perhaps incorrectly linked?

![Screenshot from 2021-06-23 14-55-44](https://user-images.githubusercontent.com/151346/123100334-50443500-d433-11eb-9a8b-66be93d075a8.png)

Is it perhaps linked to a one-way street that you can't actually drive out of?

**Comment by flaktack** [comment]
After adding f3bf9f21b and 6bd30f2 the flex trips were better, but in some cases `walkReluctance` had to higher for "normal" trips to go all the way to the station (it seems it is faster to walk the last two stops to the station than taking the bus).

**Comment by leonardehrenfried** [comment]
I think increasing walk reluctance by default wouldn't be a bad idea. What value did you have to increase it to?

**Comment by flaktack** [comment]
A value of `walkReluctance = 2.1` is enough, while the default is `2.0`. 

This plan can be used to experiment with, by putting the value in the text box: [example](https://api.dev.stadtnavi.eu/?module=planner&fromPlace=48.60232515900329%2C8.89068603515625&toPlace=48.68832569848499%2C9.002695083618164&time=11%3A00pm&date=06-16-2021&mode=FLEX_ACCESS%2CWALK%2CTRANSIT&maxWalkDistance=4828.032&arriveBy=false&wheelchair=false&debugItineraryFilter=false&locale=en&itinIndex=0)

**Comment by leonardehrenfried** [comment]
Thanks for that.

Do you share my analysis that there is a problem when driving out of bus terminal in front of the train station?

I can see other trips that depart from from the south west of the bus terminal.

![Screenshot from 2021-06-23 17-03-40](https://user-images.githubusercontent.com/151346/123121159-3a3f7000-d445-11eb-8f51-49836febb6df.png)

https://dev.stadtnavi.eu/reiseplan/Bahnhofstra%C3%9Fe%2017%2C%2071083%20Herrenberg%3A%3A48.59344171338108%2C8.863477706909181/Rudolfweg%2012%2C%2071083%20Herrenberg%3A%3A48.59999801755946%2C8.888626098632814/onDemandTaxi?time=1624480200

**Comment by leonardehrenfried** [comment]
Just to test this theory I've harmonised the access tags for those two OSM ways: https://www.openstreetmap.org/changeset/106846685

This means that driving in has the same access permissions as driving out of the terminal: `motor_vehicle=no`

https://www.openstreetmap.org/way/28799956

To me this seems nothing overly specific to us (so not mapping for just our use case) but this doesn't mean that this isn't a bug in OTP.

**Comment by leonardehrenfried** [comment]
Tomorrow morning, after the data has propagated to the Geofabrik download mirrors, I will build a graph again and test.

**Comment by flaktack** [comment]
I downloaded a copy of the updated OSM data, and it solves the above transfer, flex trips from that stop may be used.

![image](https://user-images.githubusercontent.com/58879/123130997-8ee6e900-d44d-11eb-9360-83f3d2e41cbe.png)

It seems that the changes mentioned above (f3bf9f2 and 6bd30f2) are not needed, trips seem to be planned as expected.

**Comment by leonardehrenfried** [comment]
![Screenshot from 2021-06-24 08-58-19](https://user-images.githubusercontent.com/151346/123217444-deb7c580-d4ca-11eb-9a85-d6d21ad618d1.png)

Indeed, with the updated OSM it works as expected.
