### ISSUE TITLE
Bicycle routing: footway=permissive and barrier with bicycle=no not respected

### ISSUE THREAD

**Issue by hbruch** [mfdz/OpenTripPlanner#116]
## Expected behavior
Ways tagged with footway=permissive as well as barriers with bicycle=no should not be used for bicycle routing

## Observed behavior
https://herrenberg.stadtnavi.de/reiseplan/Bismarckstra%C3%9Fe%206%2C%2071083%20Herrenberg%3A%3A48.59383908937094%2C8.867608308792116/G%C3%BCltsteiner%20Stra%C3%9Fe%2C%2071083%20Herrenberg%3A%3A48.5937220056987%2C8.870800137519838/bike?mapMode=bicycle&time=1624611637
<img width="909" alt="grafik" src="https://user-images.githubusercontent.com/2187389/123399656-2d399280-d5a5-11eb-94e9-6f6955ced248.png">

**Comment by flaktack** [comment]
The gates ([1](https://www.openstreetmap.org/node/683070347), [2](https://www.openstreetmap.org/node/683070343)) for the cemetery contain `barrier=gate` `bicycle=no` `foot=yes`.

This PR may be of use: https://github.com/HSLdevcom/OpenTripPlanner/pull/165

**Comment by leonardehrenfried** [comment]
That's a good find!

Would you like to upstream it and include a routing test like this: https://www.openstreetmap.org/directions?engine=fossgis_osrm_bike&route=48.59383%2C8.86863%3B48.59362%2C8.87075#map=19/48.59327/8.86969

(BTW, OTP is not the only one not taking the gates into account: GraphHopper does so, too).

**Comment by leonardehrenfried** [comment]
![Screenshot from 2021-07-13 12-00-44](https://user-images.githubusercontent.com/151346/125432898-7fdbecd2-cb49-4075-9de8-2242b9b604a7.png)
