### ISSUE TITLE
OTP2 upstreaming status

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/OpenTripPlanner#47]
Features | Upstream ticket | Upstream PR | Status
------------ | ------------- | ---------------------- | -----------
2.2 Free-floating bike sharing | | | [WIP upstream](https://github.com/opentripplanner/OpenTripPlanner/pull/3370), waiting to plan more work
2.2.1 same-station-based-with-temporary-drop-off | | | waiting to plan more work
2.2.2 Subtask: Add leg alerts to Graphql schema | | | waiting to plan more work
2.3 Dynamically added parking lots | https://github.com/opentripplanner/OpenTripPlanner/issues/3395
2.3.1 Wheelchair accessible parking lots | https://github.com/opentripplanner/OpenTripPlanner/issues/3395
2.4 GermanyWayPropertySet |  | https://github.com/opentripplanner/OpenTripPlanner/pull/3405 | ✅ merged
2.5 Respect bicycle route relations | https://github.com/opentripplanner/OpenTripPlanner/issues/3397 | https://github.com/opentripplanner/OpenTripPlanner/pull/3405 | ✅ merged
2.5.1 Subtask: Logical OR for mixins | https://github.com/opentripplanner/OpenTripPlanner/issues/3397 | https://github.com/opentripplanner/OpenTripPlanner/pull/3405 | ✅ merged
2.6.1 Split edges and turn restrictions | https://github.com/opentripplanner/OpenTripPlanner/issues/2965 | https://github.com/opentripplanner/OpenTripPlanner/pull/3414 | ✅ merged
2.7 Allow loops when close to start or end | https://github.com/opentripplanner/OpenTripPlanner/issues/3393 | https://github.com/opentripplanner/OpenTripPlanner/pull/3399 | ✅ merged
2.8 Separate no-through for bicycle | https://github.com/opentripplanner/OpenTripPlanner/issues/3396 | https://github.com/opentripplanner/OpenTripPlanner/pull/3410 | ✅ merged
2.9 Separate cost model for bicycle turns | https://github.com/opentripplanner/OpenTripPlanner/issues/3398 | https://github.com/opentripplanner/OpenTripPlanner/pull/3405 | ✅ merged
2.10 Fan-out park & ride requests (optional)

**Comment by t2gran** [comment]
@leonardehrenfried Thank you for calling in today.

Feel free to post this issue to the main OTP project. Then it become visible to others and you might get some feedback on the witch features others would like to se in the project. 

I forgot to mention the OTP2 Sandbox model, I think you aware of it? I have not looked at the features above yet, so I do not know if they are "Sandbox" features or main features. 

Are you using Slack? Entur is hosting a Slack channel for coordinating development work in OTP2. I can invite your organisation (if you have a professional licence) or invite developers from your team directly. Let me know if you are interested.

**Comment by t2gran** [comment]
I looked at the polyline tool, I think it looks great, I was afraid of a much more complicated "framework". I am in favor of include it :+1:. Is the https://leonard.io/polyline-visualiser code OpenSource? If you stop supporting the endpoint, it would be great if we can set it up.

**Comment by leonardehrenfried** [comment]
> Feel free to post this issue to the main OTP project. Then it become visible to others and you might get some feedback on the witch features others would like to se in the project. I will comment on each item in the list, when you do so. Alternatively you can create an issue for each bullet point. But, I think it would be great to have "your rode map" as an high level issue issue/epic. It is ok to reference the issues in you fork/repo from it.
> 
> I forgot to mention the OTP2 Sandbox model, I think you aware of it? I have not looked at the features above yet, so I do not know if they are "Sandbox" features or main features.

Yes, we are aware. IMO, most of them are bug fixes for the street routing so I don't think that they are sandbox features. However, we build a small class that also calculates a complete car route when you do park & ride. This one sounds to me like a sandbox feature.

We also talked about the free-floating rental bike. Do you think this belongs in the sandbox?

> 
> Are you using Slack? Entur is hosting a Slack channel for coordinating development work in OTP2. I can invite your organisation (if you have a professional licence) or invite developers from your team directly. Let me know if you are interested.

We'd love to join Slack. @hbruch will get in touch to coordinate.

**Comment by leonardehrenfried** [comment]
> I looked at the polyline tool, I think it looks great, I was afraid of a much more complicated "framework". I am in favor of include it +1. Is the https://leonard.io/polyline-visualiser code OpenSource? If you stop supporting the endpoint, it would be great if we can set it up.

Yes, it's open-source and you can find the code here: https://github.com/leonardehrenfried/polyline-visualiser

It is extremely simple since it is a single, self-contained HTML file. Deployment could not be easier and I'm happy to send a PR to add it to the OTP documentation website.

**Comment by t2gran** [comment]
> We also talked about the free-floating rental bike. Do you think this belongs in the sandbox?

No, I think there are many users and it need to be integrated into the routing. But, it might be useful to be able to turn it on/off via the OtpFeature.

@hbruch I you send me an email, I can send you a channel invite: thomas.gran@entur.org
