### ISSUE TITLE
Add car park map layer to vector tile API

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/OpenTripPlanner#50]
OTP2 has recently added sandbox support for vector tile layers that are very useful for stadtnavi. So far there isn’t a layer in the sandbox for car parks but there is existing code for other entities so it should be relatively straightforward.
All the properties from section 2.3 should be returned in the car park vector layer.

Depends on #48

**Comment by flaktack** [comment]
Is there an explicit list of the expected properties? What does section 2.3 cover?

**Comment by leonardehrenfried** [comment]
We would like:

- name
- total number of car/bike/accessible spaces
- free number of car/bike/accessible spaces
- opening hours
- url
- state
- tags
