### ISSUE TITLE
Wheelchair-accessible parking lots

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/OpenTripPlanner#51]
When the wheelchair-accessible flag is set on the routing request only those parking lots should be included in the route. Conversely, if it is not set then these parking spaces should be excluded.

This has already been implemented in OTP1: https://github.com/mfdz/OpenTripPlanner/pull/45

Depends on #48

**Comment by leonardehrenfried** [comment]
Estimation: 1/2/1 days

**Comment by flaktack** [comment]
#99 adds the required functionality
