### ISSUE TITLE
Add ParkAPI updater

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/OpenTripPlanner#55]
Depends on #48 

[ParkAPI](https://github.com/offenesdresden/ParkAPI/) is a somewhat popular standard in Germany for describing availability of parking lots. Herrenberg has a feed available at https://api.stadtnavi.de/herrenberg/parking/parkapi.json

We want to use it to pull the data into OTP.

Original PR: https://github.com/mfdz/OpenTripPlanner/pull/48

**Comment by flaktack** [comment]
https://api.stadtnavi.de/herrenberg/parkapi.json results in a `404 Not Found` :no_good:

**Comment by leonardehrenfried** [comment]
Sorry, I corrected it. The URL is https://api.stadtnavi.de/herrenberg/parking/parkapi.json

**Comment by leonardehrenfried** [comment]
Is there a branch I can take a look at?

**Comment by leonardehrenfried** [comment]
There is https://github.com/realCity/OpenTripPlanner/commits/feature/vehicle-parking-updaters

What is its state?

**Comment by flaktack** [comment]
There is an open PR with the changes: https://github.com/mfdz/OpenTripPlanner/pull/84
