### ISSUE TITLE
Add request parameter to only show bike park & ride routes using bike lockers

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/OpenTripPlanner#59]
Depends on #52 

A user should have the ability to specify that she only wants to use a bike locker when searching for bike park & ride routes.

**Comment by flaktack** [comment]
This should be possible using #84

**Comment by leonardehrenfried** [comment]
Estimation: 1/2/1 days

**Comment by flaktack** [comment]
#99 adds the required functionality to the ParkAPI updater:
 * `tags` can be defined in `router-config.json`
 * the `forecast`, `lot_type`, `address` and `state` tags are copied from the `lot` definition

Example tags:
```
      {
        "tags": [
          "lot_type:Fahrradabstellanlage",
          "address:Stuttgarter Str. 90-92",
          "forecast:false",
          "state:open",
          "bike-locker"
        ]
      },
```
