### ISSUE TITLE
Complete bike no-thru PR upstream

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/OpenTripPlanner#61]
I'm almost done with the upstream PR https://github.com/opentripplanner/OpenTripPlanner/pull/3410 but there was a last correction requested: 

The definition of what OSM tags should lead to a street being classified as no-thru should happen in the way property set. This is because in the US agricultural and forrestry tracks are no-thru while in Norway and Germany (perhaps all of Europe) they are not.

**Comment by leonardehrenfried** [comment]
@dominikjambor I saw your PR so have a request: can you please re-add the agricultural and forestry ways to the car no through for the default way property set?

Can you also add a separate, shared implementation for the European way property sets that does not make those kinds of ways no-thru?

Lastly, since I already created a PR, can you make https://github.com/mfdz/OpenTripPlanner/tree/bike-no-thru the target of your PR? You can then delete this one https://github.com/opentripplanner/OpenTripPlanner/pull/3424

**Comment by dominikjambor** [comment]
@leonardehrenfried The PR was a WIP for which I mistakenly selected the original repo instead of our forked one. I closed it immediately, but unfortunately PRs can not be deleted completely as far as I know. I'll select your branch as the target when I've looked into your other requests.

**Comment by leonardehrenfried** [comment]
:+1:
