### ISSUE TITLE
Add request parameter for excluding parking lots that have few spaces available

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/OpenTripPlanner#62]
Depends on #48

For a definition of "few places" check https://github.com/mfdz/OpenTripPlanner/blob/master/src/main/java/org/opentripplanner/routing/car_park/CarPark.java#L97-L107

**Comment by flaktack** [comment]
Would it be possible to handle this using the the `forecast` field in ParkAPI -- and then the actual request could ban a tag of `forecast:almost_full` (or whatever value is used)? This would require no changes on OTP's side, since the required features are all supported once #99 is merged.

**Comment by leonardehrenfried** [comment]
Ok, so the idea is that the updater just sets the tag at graph update time rather than the graph traversal checking the capacity right now?

**Comment by flaktack** [comment]
Yes.

**Comment by leonardehrenfried** [comment]
Then that's fine.
