### ISSUE TITLE
Create an upstream overview issue for B+R/P+R changes

### ISSUE THREAD

**Issue by flaktack** [mfdz/OpenTripPlanner#63]
_I thought it would be useful to create an upstream issue with an overview of the proposed B+R/P+R changes. Feel free to edit, remove things which might not be needed. :pen:_

`place.vehicleParking.{realTime,almostFull,closesSoon}` flags exist so that adding alerts based on these is simpler in stadtnavi-specific code (or in the UI).

----

The purpose of this issue is to invite discussion into the B+R/P+R changes that stadnavi and realcity would like to implement, and later to provide an overview of progress.

* [ ] Merge B+R and P+R functionality into a unified _vehicle parking_

  :speech_balloon: Is _vehicle parking_ a good name, should something else be used?

* [ ] Expose the details of the used vehicle parking in itineraries under `ApiPlace#vehicleParking`

  :speech_balloon: Currently only ids are exposed (example: `ApiPlace#bikeShareId`), is exposing the details in an object under `ApiPlace` a good direction?

* [ ] Add updaters for ParkAPI and OpenBikeBox

* [ ] Expose vehicle parking in the sandbox Mapbox Vector Tiles API

* [ ] Add support for filtering vehicle parking
  `wheelchairAccessible` - support wheelchair accessible parking spaces
  `requiredVehicleParkingTags`, `bannedVehicleParkingTags` - limit the subset of vehicle parking places which may be used by source-specific attributes

* [ ] Use real-time availability information to exclude parking lots only if reached _soon_
  `useVehicleParkingAvailabilityInformation` - this would be the pair of the existing `useBikeRentalAvailabilityInformation`
  :heavy_plus_sign: fill out `place.vehicleParking.realTime`

  :speech_balloon: What would the most user-friendly implementation be? Should this be an explicit API parameter, or automatic if the parking place is reached within 30 minutes of _now_ (which could be configured per-updater or globally in `router-config.json`)

* [ ] Allow excluding almost-full parking (if using availability information)
  `banAlmostFullVehicleParking` - [example logic](https://github.com/mfdz/OpenTripPlanner/blob/master/src/main/java/org/opentripplanner/routing/car_park/CarPark.java#L97-L107) to determine if a parking place is almost-full
  :heavy_plus_sign: fill out `place.vehicleParking.almostFull`

* [ ] Only allow parking if the parking place is open when arriving and while parking
  `useVehicleParkingOpeningHours` - explicit parameter so that trips which reach closed parking places may be planned
  :heavy_plus_sign: fill out `place.vehicleParking.closesSoon`

---

Proposed `VehicleParking` class based on the existing `BikePark`, which would support the above features:

```java
/**
 * Vehicle parking locations, which may allow bicycle and/or car parking.
 */
public class VehicleParking {

    /**
     * The id of the vehicle parking, prefixed by the source(=feedId) so that it is unique.
     */
    private FeedScopedId id;

    private String name;

    /**
     * Note: x = Longitude, y = Latitude
     */
    private double x, y;

    /**
     * Whether this station has space available information updated in real-time.
     */
    private boolean realTimeData = true;

    private String detailsUrl;

    private String imageUrl;

    /**
     * Source specific type of the vehicle parking.
     */
    private String type;

    /**
     * Source specific tags of the vehicle parking, which describe the available features.
     * For example park_and_ride, bike_lockers, or static_osm_data.
     */
    private List<String> tags;

    // TODO: this would need to be parsed from the OSM format
    private RepeatingTimePeriod openingHours;

    private RepeatingTimePeriod feeHours;

    private I18NString note;

    private VehicleParkingState state;

    private boolean bicyclePlaces;

    private boolean carPlaces;

    private boolean wheelchairAccessibleCarPlaces;

    private Capacity capacity;

    private Availability availability;

    public String toString() {
        return String.format(Locale.US, "VehicleParking(%s at %.6f, %.6f)", name, y, x);
    }

    /**
     * The total number of spaces by type. -1 indicates unknown.
     */
    @Data
    @Builder
    public static class Capacity {

        private int bicycleSpaces = -1;
        private int carSpaces = -1;
        private int wheelchairAccessibleCarSpaces = -1;
    }

    /**
     * The number of free spaces by type. -1 indicates unknown.
     */
    @Data
    @Builder
    public static class Availability {

        private int bicycleSpaces = -1;
        private int carSpaces = -1;
        private int wheelchairAccessibleCarSpaces = -1;
    }

    /**
     * The state of the vehicle parking. TEMPORARILY_CLOSED and CLOSED are distinct states so
     * that they may be represented differently to the user.
     */
    public enum VehicleParkingState {OPERATIONAL, TEMPORARILY_CLOSED, CLOSED}
}
```

**Comment by leonardehrenfried** [comment]
I think the proposed class is a good design and would support upstreaming it.

## Comments to questions

I like the name vehicle parking. Or at least I cannot think of a better one.

Parking lot properties to add to the routing response:
- id
- name
- if it's closing soon
- if it's almost full

In our fork we added special alerts to the car leg but if we add more properties to the leg that would work too. I'm unsure so let's discuss.

After thinking about the issue I think we should never automatically excluded full parking lots as this might confuse a user that knows the area. We should display a warning in the UI though.

Look forward to discussing these points.

**Comment by flaktack** [comment]
I've created an upstream issue (https://github.com/opentripplanner/OpenTripPlanner/issues/3432).
