### ISSUE TITLE
GTFS-Flex routing doesn't find itineraries or is slow

### ISSUE THREAD

**Issue by derhuerst** [mfdz/OpenTripPlanner#64]
## Expected behavior

As part of https://github.com/stadtnavi/digitransit-ui/issues/350, we expect OTP2 to support on-demand public transportation: Users should be able to **take a *Ruftaxi* bus and get dropped off directly at their destination**, in Herrenberg that is within a distance of 300m from a serviced stop.

OTP2 has recently gained support for such GTFS-Flex data (https://github.com/opentripplanner/OpenTripPlanner/pull/2603,  https://github.com/opentripplanner/OpenTripPlanner/pull/3173, https://github.com/opentripplanner/OpenTripPlanner/issues/3343), so this should all work out-of-the-box.

## Observed behavior

There are several relevant "routing modes" available, please investigate if any of them satisfies our requirements:
- "Transit"
- "Transit with flex egress"
- "Transit with flex access and egress"
- "Direct flex search"

## Steps to reproduce the problem

- Use the patched VVS feed that contains GTFS Flex from https://leonard.io/stadtnavi/vvs-gtfs-flex.gtfs.zip
- Use the following OSM file: http://download.geofabrik.de/europe/germany/baden-wuerttemberg/stuttgart-regbez-latest.osm.pbf
- use a custom OTP2 build (from `https://leonard.io/stadtnavi/otp-2-gtfs-flex.jar`) that should support GTFS-Flex or compile the source code from this branch: https://github.com/mfdz/OpenTripPlanner/tree/flex-merge

Make sure that you run the right OTP2 build, it should print:

```
Version:    2.1.0-SNAPSHOT
Ser.ver.id: 7
Commit:     048656b631e9c20df12c181e38423569463f2b20
Branch:     flex-merge
Build:      2021-04-23T13:55:39+0200
```

**From `(48.64091, 8.90865)` (close to *Gartringen Bf*) to `(48.58847, 8.85550)` (close to *Herrenberg Adlerstr.*) at `2021-04-28T23:30+02`, it should compute >=1 itinerary using the `RT779` *Ruftaxi* on-demand bus with drop-off at the destination.**

Edit: It does in fact compute [an itinerary including the `RT779` on-demand-bus](http://162.55.58.204:8080/?module=planner&fromPlace=48.64091310621078%2C8.90864610671997&toPlace=48.588410379233515%2C8.855366706848145&time=11%3A30pm&date=04-28-2021&mode=FLEX_EGRESS%2CWALK%2CTRANSIT&maxWalkDistance=4828.032&arriveBy=false&wheelchair=false&debugItineraryFilter=false&locale=en&itinIndex=1), bit it's awfully slow (25s on my machine). Please investigate how to make it fast (enough).

**Comment by leonardehrenfried** [comment]
I've also discussed this with Gard, the original author of the flex code: https://entur.slack.com/archives/CAZ86FVGS/p1619174110043100
