### ISSUE TITLE
Re-add CARPOOL mode

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/OpenTripPlanner#65]
We originally planned to use the GTFS Flex code to model carpool trips but after closer inspection we abandoned that plan.

Therefore we want to re-introduce the CARPOOL mode just like @hbruch did a few years ago in OTP2

https://github.com/mfdz/OpenTripPlanner/commit/65ea1e6bd80c668324f75ebefcfd3d1daa37ad8d
https://github.com/mfdz/OpenTripPlanner/commit/4b10a33d5d9721ac6fd5ea8be4300d239bd26439

As this is unlikely to be accepted upstream, we will keep it in this repo.

**Comment by flaktack** [comment]
This is only an extra `TraverseMode.CARPOOL` -- nothing more needs to be done, since it will come from GTFS/GTFS-realtime?

**Comment by leonardehrenfried** [comment]
Exactly.

**Comment by hbruch** [comment]
Our generated GTFS current uses route_type 1700, this would need to be mapped to this mode.

**Comment by leonardehrenfried** [comment]
I just tried it and it seems that the mode CARPOOL isn't accepted by the (legacy) GraphQL API. Can you fix this, @flaktack?

**Comment by flaktack** [comment]
I will look into it, the [README](https://github.com/mfdz/OpenTripPlanner/blob/dev-2.x/src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/README.md) contains a not-too-promising:
> TODO fix this as it currently does not run and uses wrong version of @graphql-codegen/java

**Comment by leonardehrenfried** [comment]
If you can figure this out, great, but it's not a must.

**Comment by leonardehrenfried** [comment]
@flaktack I just deployed your latest changes and you can now query for the CARPOOL mode but you don't get any results.

In OTP1/DT1 it works: https://tinyurl.com/yfzz3fcr
In OTP/DT2 it doesn't: https://tinyurl.com/yfybfp63 (you might need to open the panel and disable everything other than carpool)

Can you investigate what's the problem here? I will send you a link to the Carpool feed.

**Comment by leonardehrenfried** [comment]
My gut feeling is that some glue code is missing.

**Comment by flaktack** [comment]
The graph made using otp2-setup doesn't seem to download OSM data around Tübingen, it only downloads [Regierungsbezirk Stuttgart](http://download.geofabrik.de/europe/germany/baden-wuerttemberg/stuttgart-regbez.html):

https://github.com/stadtnavi/otp2-setup/blob/4c26c78d00aa1028232d71c4462aed451260b915/Makefile#L12-L14

![image](https://user-images.githubusercontent.com/58879/117405817-8160b880-af0c-11eb-85e9-5a74e83c8771.png)

**Comment by flaktack** [comment]
I see that the server here has different OSM data: https://api.dev.stadtnavi.eu/

**Comment by leonardehrenfried** [comment]
Yeah, sorry, that was a bit stupid of me. But you should also be able to find _some_ Carpool routes from say Herrenberg to Stuttgart.

The server has the entirety of Baden-Württemberg: http://download.geofabrik.de/europe/germany/baden-wuerttemberg.html

**Comment by flaktack** [comment]
Using [this carpool](https://www.mifaz.de/de/eintrag/092097219151008087063064), both sites work:
 * [dev](https://dev.stadtnavi.eu/reiseplan/Appenweier%2C%20Bahnhof%2C%20Bahnhofstra%C3%9Fe%2C%2077767%20Appenweier%3A%3A48.541315814562566%2C7.974019646644593/Gasthaus%20Storchen%2C%20Hauptstra%C3%9Fe%2035%2C%2077716%20Haslach%20im%20Kinzigtal%3A%3A48.27738101437895%2C8.08823347091675?time=1620277200)
 * [api.dev](https://api.dev.stadtnavi.eu/?module=planner&fromPlace=48.54133002125196%2C7.974100112915038&toPlace=48.27702399766979%2C8.088855743408203&time=7%3A00am&date=05-07-2021&mode=CARPOOL%2CWALK&maxWalkDistance=4828.032&arriveBy=false&wheelchair=false&debugItineraryFilter=false&locale=en&itinIndex=0)

**Comment by leonardehrenfried** [comment]
Ok, more stupidity on my side. I think I just had not built a graph with the carpool-reading code. :man_facepalming:
