### ISSUE TITLE
Merge Joel's island pruning PR

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/OpenTripPlanner#66]

**Comment by flaktack** [comment]
I did a quick test using this way to check the no-thru traffic handling, which was marked as no-thru traffic correctly:
https://www.openstreetmap.org/way/159830262

The PR will need to be updated to handle separate bike / car no thru traffic.

**Comment by leonardehrenfried** [comment]
And did it have an effect on the unroutable locations?

**Comment by leonardehrenfried** [comment]
Estimation: 2/5/4 days
