### ISSUE TITLE
GTFS-RT feed removes trips from results

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/OpenTripPlanner#71]
There appears to be a problem with the very latest version of OTP deployed a dev.stadtnavi.eu.

When searching from Ehningen to Herrenberg you will see [0 results](https://dev.stadtnavi.eu/reiseplan/Ehningen%3A%3A48.6592556%2C8.9405097/Herrenberg%3A%3A48.595557%2C8.8674715?time=1620390600) however, when you search for a departure that is [15 minutes later](https://dev.stadtnavi.eu/reiseplan/Ehningen%3A%3A48.6592556%2C8.9405097/Herrenberg%3A%3A48.595557%2C8.8674715?time=1620391500), you will find a single trip. I think that you should find more trips as the train goes every 30 minutes.

If you compare this to the [same query on the QA system](https://herrenberg.qa.stadtnavi.eu/reiseplan/Ehningen%3A%3A48.6592556%2C8.9405097/Herrenberg%3A%3A48.595557%2C8.8674715?time=1620391500) you can see that the problem doesn't appear there as several trips are returned.

### OTP versions
dev: `3bcf0f41606d3b70f681b2f355064f71d3ace246` (May 6)
QA: `3a2df966e9c9651305968ba22c6f2ea7fb98e255` (May 5)

My gut feeling is that this one of the filters introduced by @gmellemstrand this week and that we need to set the OTP2-specific filter options in our GraphQL queries.

@flaktack If you agree that this is the cause, please investigate which filters we need to set in the GraphQL query.

**Comment by leonardehrenfried** [comment]
The problem is slightly different from what I described above. The problem only appears when you search for a route from Ehningen to Herrenberg *right now*. If you go to the future or the past, you get the expeted S1 trains, that run every 30, sometimes even 15 minutes.

**Comment by gmellemstrand** [comment]
In the built-in client there is a checkbox for `Show Filtered Itineraries`. With this enabled, you can see which result has been removed by which filter.

**Comment by leonardehrenfried** [comment]
Thanks for the tip, @gmellemstrand.

I can see that it's not because of the filtering.

When I search today i only get the direct train in several hours:
![Screenshot from 2021-05-10 11-29-00](https://user-images.githubusercontent.com/151346/117638361-0b19bb80-b183-11eb-8758-aba87c2c0fb8.png)

When I search at the same time tomorrow, I see the direct train that goes every 30 minutes.
![Screenshot from 2021-05-10 11-29-14](https://user-images.githubusercontent.com/151346/117638348-06ed9e00-b183-11eb-992e-d67f96ac1f0c.png)

**Comment by leonardehrenfried** [comment]
Sorry, cannot reproduce anymore.

**Comment by leonardehrenfried** [comment]
So we found out that it's related to the GTFS-RT feed.

**Comment by leonardehrenfried** [comment]
I merged the patch and have reactivated realtime updaters on dev.

![Screenshot from 2021-06-07 13-44-42](https://user-images.githubusercontent.com/151346/121011246-b031af00-c796-11eb-9783-0503b15d152c.png)

So far so good but we lets run it for a few days before making a final judgement.

**Comment by leonardehrenfried** [comment]
Estimation: 0/5/1 days

**Comment by leonardehrenfried** [comment]
I've been running the code on dev for a few days now and cannot find any problems anymore. Can you @flaktack?

**Comment by leonardehrenfried** [comment]
If not I will activate it on beta.

**Comment by flaktack** [comment]
It should be ready for the beta, yes.
