### ISSUE TITLE
Rental bike leg is not designated as such when it's the last one

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/OpenTripPlanner#72]
![117937258-10ebda00-b306-11eb-8a69-13cafd0a4415](https://user-images.githubusercontent.com/151346/118288020-4d6d3080-b4d4-11eb-97e4-1f2b67d518de.png)

When making a routing request that has a final bike rental leg because it isn't being returned to a station, the API response says that this leg is 

```
bikeRental: false
```
which is incorrect. Should of course be `true`.

Steps to reproduce:

- Go to https://dev.stadtnavi.eu
- Search for a route from Ehningen to Kuppingen
- Open settings panel and disable bus and enable bike rental (RegioRad)
- Inspect the API call to see the incorrect response

**Comment by flaktack** [comment]
This is related to https://github.com/opentripplanner/OpenTripPlanner/issues/3474 along with https://github.com/opentripplanner/OpenTripPlanner/pull/3190

And this should fix it: https://github.com/opentripplanner/OpenTripPlanner/pull/3190/commits/40dd56101ff9423165202efcab5f1c532083ed01
