### ISSUE TITLE
Short PR routes include mostly driving and almost no public transport

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/OpenTripPlanner#73]
After having tested the upstream PR https://github.com/opentripplanner/OpenTripPlanner/pull/3480 I noticed that I'm seeing very few results which use the available P+R infrastructure in the Herrenberg area.

We would expect routes like these: https://tinyurl.com/ygnbfq98

But instead were seeing driving directly into Herrenberg:

![Screenshot from 2021-05-18 12-38-11](https://user-images.githubusercontent.com/151346/118637535-354c2880-b7d6-11eb-90aa-a327e62bc97c.png)

The [P+R in Nufringen](https://www.openstreetmap.org/way/528636490) looks ok in the traversal permission layer

![Screenshot from 2021-05-18 12-38-36](https://user-images.githubusercontent.com/151346/118637527-33826500-b7d6-11eb-8832-e998bec051ec.png)

Steps to reproduce

- Clone https://github.com/stadtnavi/otp2-setup/
- Compile your OTP branch and place a file called otp.jar into the root of `otp2-setup`
- `make build-stuttgart run-stuttgart`
- Plan a P+R route from Nufringen to Herrenberg

**Comment by leonardehrenfried** [comment]
I don't need to enable P+R parsing from OSM, do I? It's enabled by dafault, correct?

**Comment by richardkoszegi** [comment]
I got the same plan at first, but when I decreased the `maximum car` parameter to `1 mi`, I got the expected plan [(link)](http://localhost:8080/?module=planner&fromPlace=48.62265470565803%2C8.888025283813477&toPlace=48.59437483240996%2C8.862930536270142&time=12%3A47pm&date=05-18-2021&mode=CAR_PARK%2CTRANSIT&maxWalkDistance=1609.34&arriveBy=false&wheelchair=false&debugItineraryFilter=false&locale=en&itinIndex=1).

We can solve this by:
* decreasing the default value of the `max walk / car` parameter
* compare the car only and p+r routes weights and modify them
* disallow the `non-transit` routes int p+r mode(s)

Default values in OSM parsing:
* `staticBikeParkAndRide: false`
* `staticParkAndRide: true`

So car parkings are enabled by default, but bike parks don't.

**Comment by leonardehrenfried** [comment]
I think that a fixed maximum would not be a good solution but something like a driving reluctance would.

However, it seems it's not a problem with your code as such but with OTP2 in general.

![Screenshot from 2021-05-18 13-41-36](https://user-images.githubusercontent.com/151346/118645121-d17a2d80-b7de-11eb-8b42-6e0e27b423f5.png)

**Comment by leonardehrenfried** [comment]
![Screenshot from 2021-05-18 14-03-28](https://user-images.githubusercontent.com/151346/118647642-da203300-b7e1-11eb-8f4c-e820a4abb10b.png)

After speaking to Gard from upstream I looked at the filtered itineraries and there is a filter that filters out trips which are slower when you use transit. In our case this is however precisely what we want. 

We need to modify this class: https://github.com/opentripplanner/OpenTripPlanner/blob/482b39f3e09887e2f76fbcfffd9d743e4e1948e2/src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/RemoveTransitIfStreetOnlyIsBetterFilter.java#L16

@flaktack Can you make a suggestion here?

**Comment by flaktack** [comment]
I'm not sure what a good approach would be -- we'll think about it.

1. The filtering could be modified to check for higher cost & longer traversal times when removing alternatives
2. The cost for the direct and transit options could be checked to make sure they are "similar", reflect expectations

**Comment by flaktack** [comment]
My impression here is that the costs for access / egress are somewhat off ([using this request](https://api.dev.stadtnavi.eu/?module=planner&fromPlace=48.62224337239389%2C8.889248371124268&toPlace=48.591014813615324%2C8.860623836517334&time=12%3A23pm&date=05-19-2021&mode=CAR_PARK%2CTRANSIT&maxWalkDistance=4828.032&arriveBy=false&wheelchair=false&debugItineraryFilter=false&locale=en&itinIndex=0)). *If* the cost of the P+R all the way was more realistic, than the filter would work-as-expected.

* walk all the way (**6102**)
![image](https://user-images.githubusercontent.com/58879/118799836-7fe5a780-b89f-11eb-9472-3e3eb377e9f0.png)
* walk & train (**2059**)
![image](https://user-images.githubusercontent.com/58879/118799906-9429a480-b89f-11eb-800d-62db4b979eb4.png)
* P+R all the way (**1696**)
  ![image](https://user-images.githubusercontent.com/58879/118799703-53319000-b89f-11eb-8c2e-e54f1e3e1677.png)
* P+R to the train station (**4036**)
  ![image](https://user-images.githubusercontent.com/58879/118799783-6d6b6e00-b89f-11eb-912f-171430e7f702.png)

**Comment by leonardehrenfried** [comment]
How is waiting penalized?

**Comment by flaktack** [comment]
Waiting before transit (at the beginning) is not penalized, but waiting for transfers is. A* and RAPTOR calculate leg costs differently, which is the reason for the difference (I'm still looking to understand how the calculations work).

**Comment by leonardehrenfried** [comment]
Estimation: 1/2/1 days
