### ISSUE TITLE
Duplicate car legs for P+R routes

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/OpenTripPlanner#74]
When planning P+R trip we see duplicate car legs, presumably passing through the parking lot.
![Screenshot from 2021-05-20 15-58-00](https://user-images.githubusercontent.com/151346/118991653-33c06300-b984-11eb-9cd2-6afd9a7edf3f.png)

[Example](https://dev.stadtnavi.eu/reiseplan/Wuschels%20Backstub%2C%20Enzstra%C3%9Fe%206%2C%2071083%20Oberjesingen%3A%3A48.62320787269338%2C8.83403778076172/Kalkofenstra%C3%9Fe%2C%2071083%20Herrenberg%3A%3A48.59505958179822%2C8.862147331237795/parkAndRide?time=1621518870)

**Comment by flaktack** [comment]
Which OTP2 version is this with?

**Comment by leonardehrenfried** [comment]
It's this: https://github.com/mfdz/OpenTripPlanner/tree/dev-2.x

It's basically upstream + CARPOOL + https://github.com/mfdz/OpenTripPlanner/commit/d8feafd22c10c0cfd85b212112d4577f56dd87d6

**Comment by leonardehrenfried** [comment]
Is this going to be fixed with the vehicle parking PR?

**Comment by flaktack** [comment]
It _should_ be fixed, but I'll double check.
