### ISSUE TITLE
Duplicate walk legs with BIKE_PARK

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/OpenTripPlanner#95]
https://herrenberg.beta.stadtnavi.eu/reiseplan/Bahnhof%20Herrenberg%2C%20Bahnhofstra%C3%9Fe%2014%2C%2071083%20Herrenberg%3A%3A48.593861700000005%2C8.86307270000001/Vorsteigstra%C3%9Fe%2C%2070193%20Stuttgart%3A%3A48.7812373%2C9.1553375/bikeAndVehicle/0?mapMode=bicycle&time=1622828190

![Screenshot from 2021-06-07 13-37-25](https://user-images.githubusercontent.com/151346/121010280-80ce7280-c795-11eb-9bc2-d628b756ee75.png)

**Comment by leonardehrenfried** [comment]
Estimation: 1/1/1 day

**Comment by flaktack** [comment]
This should be fixed by #96
