### ISSUE TITLE
Disallow bike rentals with a negative availability

### ISSUE THREAD

**Issue by leonardehrenfried** [mfdz/OpenTripPlanner#98]
We have car rentals in OTP but only for displaying the stations on the map and usually you cannot get any routes with them as their availability is always -1.

However, if a user searches in the future the availability information is not used and user _can_ get those routes, which results in a very poor UI:

![image](https://user-images.githubusercontent.com/151346/121310772-01ab7c80-c904-11eb-8326-57ede50052dc.png)

Please disallow traversing bike rental nodes in any case if the availability is negative.

**Comment by flaktack** [comment]
Would specifying `bannedBikeRentalNetworks` be sufficient?

**Comment by leonardehrenfried** [comment]
I didn't know it exists. What happens when you set both allowed and banned bicycle networks?

**Comment by leonardehrenfried** [comment]
Looks like it does what we want: https://github.com/opentripplanner/OpenTripPlanner/blob/c2a6d39ed7a79bfdb91996163e09415657d537f6/src/main/java/org/opentripplanner/routing/edgetype/BikeRentalEdge.java#L148

**Comment by leonardehrenfried** [comment]
Thanks for the tip.

**Comment by leonardehrenfried** [comment]
I tried it and it does exactly what we want. :+1:
